// generate-robots-txt: serves robots.txt with sitemap reference.
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const SITE_URL = Deno.env.get("SITE_URL") || "https://waxapp.mx";
const SITEMAP_URL = `https://${Deno.env.get("SUPABASE_URL")?.replace(/^https?:\/\//, "").split(".")[0]}.supabase.co/functions/v1/generate-sitemap`;

Deno.serve((req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const body = `# robots.txt — generated by Lovable Cloud
User-agent: *
Allow: /
Disallow: /admin
Disallow: /admin/*
Disallow: /cliente
Disallow: /mi-cuenta
Disallow: /checkout
Disallow: /reset-password

Sitemap: ${SITE_URL}/sitemap.xml
Sitemap: ${SITEMAP_URL}
`;

  return new Response(body, {
    headers: { ...corsHeaders, "Content-Type": "text/plain; charset=utf-8" },
  });
});
