// generate-robots-txt: serves robots.txt with sitemap reference.
// Multi-domain aware: resolves the host from ?host= or x-forwarded-host
// and emits Sitemap: pointing to the matching domain.
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
};

const KNOWN_HOSTS = ["waxapp.mx", "vapewax.com.mx", "extraccionwax.com"];
const DEFAULT_HOST = (Deno.env.get("SITE_URL") || "https://waxapp.mx").replace(/^https?:\/\//, "");
const FALLBACK_SITEMAP = `https://${(Deno.env.get("SUPABASE_URL") || "").replace(/^https?:\/\//, "").split(".")[0]}.supabase.co/functions/v1/generate-sitemap`;

const resolveHost = (req: Request): string => {
  const url = new URL(req.url);
  const fromQuery = url.searchParams.get("host");
  const fromHeader = req.headers.get("x-forwarded-host") || req.headers.get("host") || "";
  const candidate = (fromQuery || fromHeader).toLowerCase().replace(/^www\./, "").split(":")[0];
  return KNOWN_HOSTS.includes(candidate) ? candidate : DEFAULT_HOST;
};

Deno.serve((req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const host = resolveHost(req);
  const body = `# robots.txt — generated by Lovable Cloud (multi-domain)
User-agent: *
Allow: /
Disallow: /admin
Disallow: /admin/*
Disallow: /cliente
Disallow: /mi-cuenta
Disallow: /checkout
Disallow: /reset-password

Host: ${host}
Sitemap: https://${host}/sitemap.xml
Sitemap: ${FALLBACK_SITEMAP}?host=${host}
`;

  return new Response(body, {
    headers: { ...corsHeaders, "Content-Type": "text/plain; charset=utf-8" },
  });
});
